version: '3'

services:
  voting-client:
    image: louisga/sms-voting:latest
    container_name: voting-app
    env_file:
      - ./voting-client.env
    depends_on:
      - voting-database
    volumes:
      - ./candidate-images:/voting-app/src/main/resources/static/images/candidates
    networks:
      - voting-network
    ports:
      - '9000:8080'

  voting-database:
    image: mysql:5.7
    container_name: voting-db
    restart: always
    env_file:
      - ./voting-database.env
    command: mysqld --lower_case_table_names=1 --character_set_server=utf8 --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=ON
    volumes: 
      - voting-database:/var/lib/mysql
    networks:
      - voting-network
    ports:
      - '3306:3306'


volumes:
  voting-database:
#  candidate-images:

networks:
  voting-network:
    driver: bridge